<script src="/assets/js/app/basico/categoria/index.js"></script>	

<div class="container">
	<div class="crumbs">
		<ul class="breadcrumb" id="breadcrumbs">
			<li>
				<i class="icon-home"></i>
				<a href="/">Dashboard</a>
			</li>
			<li>
				<a title="" href="#">Cadastro</a>
			</li>
			<li class="current">
				<a title="" href="/cadastro/categoria">Categoria</a>
			</li>
		</ul>		
	</div> <!-- /.crumbs -->	
	
	<div class="page-header">
		<div class="page-title">
			<h3>Categoria</h3>
			<span>Crie, altere, remova</span>
		</div>

		<!-- Page Stats -->
		<ul class="page-stats">            
			<li>
                <a class="btn btn-primary" id="btnNovaCategoria" data-link="/cadastro/categoria/new">Nova Categoria</a>                
			</li>
		</ul>
		<!-- /Page Stats -->
	</div>
	
	<!-- Modal dialog -->
	<div class="modal-dialog modal-sm" id="myModal1"></div>
	
	
	<div class="modal fade" id="myModal2">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Modal title</h4>
				</div>
				<div class="modal-body">
					One fine body&hellip;
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	<!-- /.modal -->
	
	<!--=== no-padding and table-tabletools ===-->
	<div class="row">
		<div class="col-md-12">
			<div class="widget box">
				<div class="widget-header">
					<h4><i class="icon-reorder"></i> Suas Categorias </h4>
					<div class="toolbar no-padding">
						<div class="btn-group">
							<span class="btn btn-xs widget-collapse"><i class="icon-angle-down"></i></span>
						</div>
					</div>
				</div>
				<div class="widget-content no-padding">
					<table class="table table-striped table-bordered table-hover table-checkable table-tabletools datatable">
						<thead>
							<tr>
								<th>#</th>
								<th>Tipo</th>
								<th>Categoria</th>
								<th>Status</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>1</td>
								<td>Receita</td>
								<td>Salário</td>
								<td><span class="label label-success">Ativa</span></td>
							</tr>
							<tr>
								<td>2</td>
								<td>Receita</td>
								<td>Hora Extra</td>
								<td><span class="label label-success">Ativa</span></td>
							</tr>
							<tr>
								<td>3</td>
								<td>Despesa</td>
								<td>Seguro Carro</td>
								<td><span class="label label-warning">Inativa</span></td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<!-- /no-padding and table-tabletools -->
	
</div>
<!-- /.container -->
